protag = input("name of a person\n")
homie1= input("name of another person\n")
homie2 = input("name of a dude\n")
animal = input("an animal\n")
obj1= input("object\n")
vehicle = input("vehicle\n")

print("\n\n"+protag+" and their homies " + homie1 + " & " + homie2 + " was cruising around in their " + vehicle +".\n")
print("Suddenly, a " + animal + " walked out onto the road and the " + vehicle + " ran them over!\n")
print("This " + animal + " wasn't any ordinary " + animal +", it was sentient.\n")
print("In it's last dying breaths, it handed " + protag + " a " + obj1 + " rolled up into, for legal reasons, a 'tube'.\n")
print("'Smoke this' the " + animal + " rasped, 'it's sum real good kush.' and with that, it died\n")
print(protag+ ", "+homie1+", and "+homie2+" all lit up and it was wild\n")
print("They were all trippin': " +protag+" was seeing Bethoven rizzing up their girl, "+homie1+" was seeing a cult, all performing the ritual of 6 7, and, "+homie2+" saw beautiful, beautiful cups of matcha tipping over and spiling,'MY MATCHAAA!!!', he cried. "+homie2+" ,being the performative male he is, promptly died of the mental anguish of it all.\n")
print(protag+" and "+homie1+"'s arrests were the natural conclusion of tripping of off "+obj1+". NEVER, do a 'tube' of "+obj1+".\n")
